name: first

on: push

jobs:
	first job:
		runs-on: macos-latest
		steps:
		- name: Step 1
			uses: actions/checkout@v2
		- name: Step 2
			run: env | sort

	second job:
		runs-on: ubuntu-latest
		steps:
		- name: Step 1
			uses: actions/checkout@v2
		- name: Step 2
			run: "Get-ChildItem Env: | Sort-Object Name"
