name: Artifact

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code 
      uses: actions/checkout@v2
    - name: Upload Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: repo
        path: .
