name: Merge Pull Request

on:
  pull_request:
    types: [opened,reopened]

jobs:
  CheckFiles:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the code
      uses : actions/checkout@v2
    - name : Python Set-up
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    

    - name: Flake8 and PyLint
     # pip install -r requirements.txt
      run: |
        flake8 --ignore=E501,E231 *.py tests/*.py
        pylint --errors-only --disable=C0326  *.py tests/*.py
          
  merge:
    needs: [CheckFiles]
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the code
      uses : actions/checkout@v2
      
      
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: managedkaos/merge-pull-request@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
