name: Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened,reopened]
    

jobs:
  lint:
  
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the code
      uses : actions/checkout@v2
    - name : Python Set-up
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Flake8 lint
      uses: py-actions/flake8@v1.1.0
    
  
          
  merge:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    
    - name : Checkout the code
      uses : actions/checkout@v2
      
    - name: Approve Action
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 1
        method: squash
  
