name: Merge Pull Request

on:
  pull_request:
    types: [opened,reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the code
      uses : actions/checkout@v2
    - name : Python Set-up
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        
    - name: FLake 8 Linting
      # You may pin to the exact commit or the version.
      # uses: julianwachholz/flake8-action@5f8a6f59421b5bdd857439c9e05984d0017ff6cd
      uses: julianwachholz/flake8-action@v2.0.0
      with:
        # The name of the check to add annotations to. Generally the same as the job that uses this action
        checkName: 
        # Path to use for flake8
        path: # optional, default is .
        # Specify a config file for flake8
        config: # optional
        # Used for internal tests
        isTest: # optional, default is false
    
          
  merge:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - name : Checkout the code
      uses : actions/checkout@v2
      
      
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: managedkaos/merge-pull-request@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
